// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/daftar-sekolah": {
            "post": {
                "description": "Daftar Akun Sekolah hanya oleh super admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Daftar Akun Sekolah (akun, kontrol sekolah -\u003e menu-menu, pendaftaran pendidik/siswa).",
                "parameters": [
                    {
                        "description": "body unutk daftar akun Sekolah",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterInputSekolah"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/daftar-siswa": {
            "post": {
                "description": "Daftar Akun Siswa table yang terdaftar ada 4 yaitu table users sebagai akun, table siswa sebagai biodata, table prestasi sebagai manajemen prestasi siswa, table asal sekolah sebagai manajemen asal sekolah siswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Daftar Akun Siswa (akun, biodata, asal sekolah, prestasi, beasiswa).",
                "parameters": [
                    {
                        "description": "body untuk daftar akun siswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterInputSiswa"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ganti-password/{username}": {
            "patch": {
                "description": "Menggati Password akun berdasarkan username.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Menggati Password akun.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body untuk ganti password",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.InputUpdatePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Users"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Logging in to get jwt token to access admin or user api by roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login as as user.",
                "parameters": [
                    {
                        "description": "the body to login a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "description": "Get a list of Role User Login.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roles"
                ],
                "summary": "Get all Roles User Login.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Roles"
                            }
                        }
                    }
                }
            }
        },
        "/sekolah/angkatan": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Membuat data Angkatan baru.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Angkatan"
                ],
                "summary": "Membuat data Angkatan barun.",
                "parameters": [
                    {
                        "description": "the body to create a new Angkatan",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.InputAngakatan"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Angkatan"
                        }
                    }
                }
            }
        },
        "/sekolah/angkatan/{id}": {
            "get": {
                "description": "Mendapatkan data angkatan berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Angkatan"
                ],
                "summary": "Mendapatkan data angkatan.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Angkatan id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Angkatan"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Menghapus Sebuah data angkatan  berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Angkatan"
                ],
                "summary": "Menghapus data angkatan.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Angkatan id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui data angkatan berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Angkatan"
                ],
                "summary": "Memperbarui data Angkatan.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Angkatan id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update Angkatan",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.UpdateInputAngakatan"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Angkatan"
                        }
                    }
                }
            }
        },
        "/sekolah/kelas": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Membuat data Kelas baru.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Kelas"
                ],
                "summary": "Membuat data Kelas barun.",
                "parameters": [
                    {
                        "description": "the body to create a new Kelas",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.InputKelas"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Kelas"
                        }
                    }
                }
            }
        },
        "/sekolah/kelas/{id}": {
            "get": {
                "description": "Mendapatkan data kelas berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Kelas"
                ],
                "summary": "Mendapatkan data kelas.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "kelas id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Kelas"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Menghapus Sebuah data Kelas  berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Kelas"
                ],
                "summary": "Menghapus data Kelas.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kelas id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui data Kelas berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Kelas"
                ],
                "summary": "Memperbarui data Kelas.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kelas id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update Kelas",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.UpdateInputKelas"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Kelas"
                        }
                    }
                }
            }
        },
        "/sekolah/pendaftaran-pendidik-aktif": {
            "get": {
                "description": "Mendapatkan semua ata sekolah yang membuka jalur pendaftaran pendidik.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "mendapatkan data sekolah yang membuka jalur pendaftaran pendidik.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Sekolah"
                            }
                        }
                    }
                }
            }
        },
        "/sekolah/pendaftaran-siswa-aktif": {
            "get": {
                "description": "Mendapatkan semua ata sekolah yang membuka jalur pendaftaran siswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "mendapatkan data sekolah yang membuka jalur pendaftaran siswa.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Sekolah"
                            }
                        }
                    }
                }
            }
        },
        "/sekolah/tahun-ajaran": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Membuat data tahun ajaran baru.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Tahun Ajaran"
                ],
                "summary": "Membuat data tahun ajaran barun.",
                "parameters": [
                    {
                        "description": "the body to create a new tahun ajaran",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.InputTahunAjaran"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TahunAjaran"
                        }
                    }
                }
            }
        },
        "/sekolah/tahun-ajaran/{id}": {
            "get": {
                "description": "Mendapatkan data tahun ajaran berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Tahun Ajaran"
                ],
                "summary": "Mendapatkan data tahun ajaran.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tahun ajaran id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TahunAjaran"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Menghapus Sebuah data tahun ajaran  berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Tahun Ajaran"
                ],
                "summary": "Menghapus data tahun ajaran.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tahun ajaran id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui data tahun ajaran berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Tahun Ajaran"
                ],
                "summary": "Memperbarui data tahun ajaran.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tahun ajaran id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update tahun ajaran",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.UpdateInputTahunAjaran"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TahunAjaran"
                        }
                    }
                }
            }
        },
        "/sekolah/tahun-ajaran/{id}/kelas": {
            "get": {
                "description": "Mendapatkan semua data kelas Berdasarkan ID Tahun Ajaran.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Kelas"
                ],
                "summary": "mendapatkan data kelas berdasarkan ID Tahun Ajaran.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tahun ajaran id  id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Kelas"
                            }
                        }
                    }
                }
            }
        },
        "/sekolah/user/{id}": {
            "get": {
                "description": "Mendapatkan data sekolah berdasarkan user ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Mendapatkan data sekolah berdasarkan user ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}": {
            "get": {
                "description": "Mendapatkan data sekolah berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Mendapatkan data sekolah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Menghapus semua data sekolah berdasarkan id. mulai dari akun, .",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa"
                ],
                "summary": "Menghapus data sekolah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/aktivasi-menu-pendidik": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Aktivasi Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Aktivasi Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/aktivasi-menu-siswa": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Aktivasi Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Aktivasi Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/angkatan": {
            "get": {
                "description": "Mendapatkan semua data angkatan Berdasarkan ID Sekolah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Angkatan"
                ],
                "summary": "mendapatkan data angkatan berdasarkan ID Sekolah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Angkatan"
                            }
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/buka-pendaftaran-pendidik": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Buka pendafatran pendidik berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Buka pendafatran pendidik berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/buka-pendaftaran-siswa": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Buka pendafatran siswa berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Buka pendafatran siswa berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/kode-verifikasi-pendaftaran-pendidik": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui kode verifikasi pendaftaran pendidik berdasarkan id sekolah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Memperbarui kode verifikasi pendaftaran pendidik.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tahun ajaran id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update kode verifikasi pendaftaran pendidik",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.UpdateInputKodeVerifikasiPendidik"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/kode-verifikasi-pendaftaran-siswa": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui kode verifikasi pendaftaran siswa berdasarkan id sekolah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Memperbarui kode verifikasi pendaftaran siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tahun ajaran id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "the body to update kode verifikasi pendaftaran siswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sekolahController.UpdateInputKodeVerifikasiSiswa"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/non-aktif-menu-pendidik": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "non aktif Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "non aktif Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/non-aktif-menu-siswa": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Non aktif Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Non aktif Menu pengisian/update biodata siswa Siswa berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/tahun-ajaran": {
            "get": {
                "description": "Mendapatkan semua data tahun ajaran Berdasarkan ID Sekolah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah -\u003e Tahun Ajaran"
                ],
                "summary": "mendapatkan data tahun ajaran berdasarkan ID Sekolah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TahunAjaran"
                            }
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/tutup-pendaftaran-pendidik": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Tutup pendafatran pendidik berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Tutup pendafatran pendidik berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/sekolah/{id}/tutup-pendaftaran-siswa": {
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Tutup pendafatran siswa berdasarkan sekolah id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Tutup pendafatran siswa berdasarkan sekolah id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Sekolah"
                        }
                    }
                }
            }
        },
        "/siswa/asal-sekolah/{id}": {
            "get": {
                "description": "Mendapatkan data asal sekolah siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Asal Sekolah"
                ],
                "summary": "Mendapatkan data asal sekolah siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "asalSekolah_siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AsalsekolahSiswas"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui data asal sekolah siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Asal Sekolah"
                ],
                "summary": "Memperbarui data asal sekolah siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "asal_Sekolah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update beasiswa Siswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/siswaController.UpdateInputAsalSekolahSiswa"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AsalsekolahSiswas"
                        }
                    }
                }
            }
        },
        "/siswa/beasiswa/{id}": {
            "get": {
                "description": "Mendapatkan data beasiswa siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Beasiswa"
                ],
                "summary": "Mendapatkan data beasiswa siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Beasiswa_siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BeasiswaSiswas"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui data beasiswa siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Beasiswa"
                ],
                "summary": "Memperbarui data beasiswa siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Beasiswa_siswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update beasiswa Siswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/siswaController.UpdateInputBeasiswaSiswa"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BeasiswaSiswas"
                        }
                    }
                }
            }
        },
        "/siswa/prestasi/{id}": {
            "get": {
                "description": "Mendapatkan data prestasi siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Prestasi"
                ],
                "summary": "Mendapatkan data prestasi siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prestasi_siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PrestasiSiswas"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui data prestasi siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Prestasi"
                ],
                "summary": "Memperbarui data prestasi siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prestasi_siswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update prestasi Siswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/siswaController.UpdateInputPrestasiSiswa"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PrestasiSiswas"
                        }
                    }
                }
            }
        },
        "/siswa/user/{id}": {
            "get": {
                "description": "Mendapatkan data siswa berdasarkan user ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa"
                ],
                "summary": "Mendapatkan data siswa berdasarkan user ID.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Siswa"
                        }
                    }
                }
            }
        },
        "/siswa/{id}": {
            "get": {
                "description": "Mendapatkan data siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa"
                ],
                "summary": "Mendapatkan data siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Siswa"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Menghapus semua data siswa berdasarkan id. mulai dari akun, biodata, asal sekolah, prestasi, beasiswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sekolah"
                ],
                "summary": "Menghapus data siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "memperbaharui data siswa berdasarkan id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa"
                ],
                "summary": "Memperbarui data Siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update Siswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/siswaController.UpdateInputSiswa"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Siswa"
                        }
                    }
                }
            }
        },
        "/siswa/{id}/asal-sekolah": {
            "get": {
                "description": "Mendapatkan data asal sekolah siswa berdasarkan id siswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Asal Sekolah"
                ],
                "summary": "Mendapatkan data asal sekolah siswa berdasarkan id siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AsalsekolahSiswas"
                        }
                    }
                }
            }
        },
        "/siswa/{id}/beasiswa": {
            "get": {
                "description": "Mendapatkan data beasiswa siswa berdasarkan id siswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Beasiswa"
                ],
                "summary": "Mendapatkan data beasiswa siswa berdasarkan id siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BeasiswaSiswas"
                        }
                    }
                }
            }
        },
        "/siswa/{id}/prestasi": {
            "get": {
                "description": "Mendapatkan data prestasi siswa berdasarkan id siswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Siswa -\u003e Prestasi"
                ],
                "summary": "Mendapatkan data prestasi siswa berdasarkan id siswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Siswa ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PrestasiSiswas"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get a list of Get All Users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all Get All Users.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Users"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.InputUpdatePassword": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.LoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.RegisterInputSekolah": {
            "type": "object",
            "required": [
                "nama",
                "password",
                "username"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.RegisterInputSiswa": {
            "type": "object",
            "required": [
                "kode_verifikasi_pendaftaran",
                "nama",
                "nisn",
                "password",
                "sekolah_id",
                "username"
            ],
            "properties": {
                "kode_verifikasi_pendaftaran": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nisn": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Angkatan": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.AsalsekolahSiswas": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jenis_sekolah": {
                    "type": "string"
                },
                "lokasi_sekolah": {
                    "type": "string"
                },
                "no_blanko_skhun": {
                    "type": "string"
                },
                "no_peserta_un": {
                    "type": "string"
                },
                "no_seri_ijazah": {
                    "type": "string"
                },
                "npsn_sekolah": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "integer"
                },
                "status_sekolah": {
                    "type": "string"
                },
                "tanggal_kelulusan": {
                    "type": "string"
                },
                "total_nilai_un": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.BeasiswaSiswas": {
            "type": "object",
            "properties": {
                "alasan_menerima_pip": {
                    "type": "string"
                },
                "besar_uang_diterima": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jangka_waktu_non_pip": {
                    "type": "string"
                },
                "jenis_beasiswa_non_pip": {
                    "type": "string"
                },
                "no_kip": {
                    "type": "string"
                },
                "no_kks": {
                    "type": "string"
                },
                "no_pkh": {
                    "type": "string"
                },
                "periode_menerima_pip": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "integer"
                },
                "status_beasiswa_non_pip": {
                    "type": "string"
                },
                "status_pip": {
                    "type": "string"
                },
                "sumber_beasiswa_non_pip": {
                    "type": "string"
                },
                "tahun_mulai_menerima_non_pip": {
                    "type": "string"
                },
                "tahun_mulai_menerima_pip": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Kelas": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                },
                "tahun_ajaran_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.PrestasiSiswas": {
            "type": "object",
            "properties": {
                "bidang_prestasi": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jenis_lomba": {
                    "type": "string"
                },
                "peringkat_lomba": {
                    "type": "string"
                },
                "peringkat_prestasi": {
                    "type": "string"
                },
                "siswa_id": {
                    "type": "integer"
                },
                "tahun_meraih_prestasi": {
                    "type": "integer"
                },
                "tingkat_lomba": {
                    "type": "string"
                },
                "tingkat_prestasi": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Roles": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "models.Sekolah": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kode_verifikasi_pendaftaran_pendidik": {
                    "type": "string"
                },
                "kode_verifikasi_pendaftaran_siswa": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "pendaftaran_pendidik": {
                    "type": "string"
                },
                "pendaftaran_siswa": {
                    "type": "string"
                },
                "status_menu_pendidik": {
                    "type": "string"
                },
                "status_menu_siswa": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Siswa": {
            "type": "object",
            "properties": {
                "agama": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "cita_cita": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desa": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "hafalan_juz": {
                    "type": "string"
                },
                "hafalan_surat": {
                    "type": "string"
                },
                "hobi": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jarak_rumah": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string"
                },
                "jumlah_saudara": {
                    "type": "string"
                },
                "kabupaten": {
                    "type": "string"
                },
                "kecamatan": {
                    "type": "string"
                },
                "kode_pos": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nama_ayah": {
                    "type": "string"
                },
                "nama_ibu": {
                    "type": "string"
                },
                "nama_wali": {
                    "type": "string"
                },
                "nik_ayah": {
                    "type": "string"
                },
                "nik_ibu": {
                    "type": "string"
                },
                "nik_siswa": {
                    "type": "string"
                },
                "nik_wali": {
                    "type": "string"
                },
                "nis_lokal": {
                    "type": "string"
                },
                "nisn": {
                    "type": "string"
                },
                "no_hp_ayah": {
                    "type": "string"
                },
                "no_hp_ibu": {
                    "type": "string"
                },
                "no_hp_siswa": {
                    "type": "string"
                },
                "no_hp_wali": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "pekerjaan_ayah": {
                    "type": "string"
                },
                "pekerjaan_ibu": {
                    "type": "string"
                },
                "pekerjaan_wali": {
                    "type": "string"
                },
                "pendidikan_ayah": {
                    "type": "string"
                },
                "pendidikan_ibu": {
                    "type": "string"
                },
                "pendidikan_wali": {
                    "type": "string"
                },
                "penghasilan_orangtua": {
                    "type": "string"
                },
                "penghasilan_wali": {
                    "type": "string"
                },
                "provinsi": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                },
                "tanggal_lahir": {
                    "type": "string"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tempat_tinggal": {
                    "type": "string"
                },
                "transportasi": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.TahunAjaran": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Users": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "sekolahController.InputAngakatan": {
            "type": "object",
            "required": [
                "nama",
                "sekolah_id"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                }
            }
        },
        "sekolahController.InputKelas": {
            "type": "object",
            "required": [
                "nama",
                "sekolah_id",
                "tahun_ajaran_id"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                },
                "tahun_ajaran_id": {
                    "type": "integer"
                }
            }
        },
        "sekolahController.InputTahunAjaran": {
            "type": "object",
            "required": [
                "nama",
                "sekolah_id",
                "semester"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                },
                "sekolah_id": {
                    "type": "integer"
                },
                "semester": {
                    "type": "string"
                }
            }
        },
        "sekolahController.UpdateInputAngakatan": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "sekolahController.UpdateInputKelas": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "sekolahController.UpdateInputKodeVerifikasiPendidik": {
            "type": "object",
            "properties": {
                "kode_verifikasi_pendaftaran_pendidik": {
                    "type": "string"
                }
            }
        },
        "sekolahController.UpdateInputKodeVerifikasiSiswa": {
            "type": "object",
            "properties": {
                "kode_verifikasi_pendaftaran_siswa": {
                    "type": "string"
                }
            }
        },
        "sekolahController.UpdateInputTahunAjaran": {
            "type": "object",
            "required": [
                "nama",
                "semester"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                },
                "semester": {
                    "type": "string"
                }
            }
        },
        "siswaController.UpdateInputAsalSekolahSiswa": {
            "type": "object",
            "properties": {
                "jenis_sekolah": {
                    "type": "string"
                },
                "lokasi_sekolah": {
                    "type": "string"
                },
                "no_blanko_skhun": {
                    "type": "string"
                },
                "no_peserta_un": {
                    "type": "string"
                },
                "no_seri_ijazah": {
                    "type": "string"
                },
                "npsn_sekolah": {
                    "type": "string"
                },
                "status_sekolah": {
                    "type": "string"
                },
                "tanggal_kelulusan": {
                    "type": "string"
                },
                "total_nilai_un": {
                    "type": "string"
                }
            }
        },
        "siswaController.UpdateInputBeasiswaSiswa": {
            "type": "object",
            "properties": {
                "alasan_menerima_pip": {
                    "type": "string"
                },
                "besar_uang_diterima": {
                    "type": "string"
                },
                "jangka_waktu_non_pip": {
                    "type": "string"
                },
                "jenis_beasiswa_non_pip": {
                    "type": "string"
                },
                "no_kip": {
                    "type": "string"
                },
                "no_kks": {
                    "type": "string"
                },
                "no_pkh": {
                    "type": "string"
                },
                "periode_menerima_pip": {
                    "type": "string"
                },
                "status_beasiswa_non_pip": {
                    "type": "string"
                },
                "status_pip": {
                    "type": "string"
                },
                "sumber_beasiswa_non_pip": {
                    "type": "string"
                },
                "tahun_mulai_menerima_non_pip": {
                    "type": "string"
                },
                "tahun_mulai_menerima_pip": {
                    "type": "string"
                }
            }
        },
        "siswaController.UpdateInputPrestasiSiswa": {
            "type": "object",
            "properties": {
                "bidang_prestasi": {
                    "type": "string"
                },
                "jenis_lomba": {
                    "type": "string"
                },
                "peringkat_lomba": {
                    "type": "string"
                },
                "peringkat_prestasi": {
                    "type": "string"
                },
                "tahun_meraih_prestasi": {
                    "type": "integer"
                },
                "tingkat_lomba": {
                    "type": "string"
                },
                "tingkat_prestasi": {
                    "type": "string"
                }
            }
        },
        "siswaController.UpdateInputSiswa": {
            "type": "object",
            "required": [
                "nama",
                "nisn"
            ],
            "properties": {
                "agama": {
                    "type": "string"
                },
                "alamat": {
                    "type": "string"
                },
                "cita_cita": {
                    "type": "string"
                },
                "desa": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "hafalan_juz": {
                    "type": "string"
                },
                "hafalan_surat": {
                    "type": "string"
                },
                "hobi": {
                    "type": "string"
                },
                "jarak_rumah": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string"
                },
                "jumlah_saudara": {
                    "type": "string"
                },
                "kabupaten": {
                    "type": "string"
                },
                "kecamatan": {
                    "type": "string"
                },
                "kode_pos": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nama_ayah": {
                    "type": "string"
                },
                "nama_ibu": {
                    "type": "string"
                },
                "nama_wali": {
                    "type": "string"
                },
                "nik_ayah": {
                    "type": "string"
                },
                "nik_ibu": {
                    "type": "string"
                },
                "nik_siswa": {
                    "type": "string"
                },
                "nik_wali": {
                    "type": "string"
                },
                "nis_lokal": {
                    "type": "string"
                },
                "nisn": {
                    "type": "string"
                },
                "no_hp_ayah": {
                    "type": "string"
                },
                "no_hp_ibu": {
                    "type": "string"
                },
                "no_hp_siswa": {
                    "type": "string"
                },
                "no_hp_wali": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "pekerjaan_ayah": {
                    "type": "string"
                },
                "pekerjaan_ibu": {
                    "type": "string"
                },
                "pekerjaan_wali": {
                    "type": "string"
                },
                "pendidikan_ayah": {
                    "type": "string"
                },
                "pendidikan_ibu": {
                    "type": "string"
                },
                "pendidikan_wali": {
                    "type": "string"
                },
                "penghasilan_orangtua": {
                    "type": "string"
                },
                "penghasilan_wali": {
                    "type": "string"
                },
                "provinsi": {
                    "type": "string"
                },
                "tanggal_lahir": {
                    "type": "string"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tempat_tinggal": {
                    "type": "string"
                },
                "transportasi": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
